version: "3"
services:
  web:
    build: .
    tty: true
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - ./app:/go/src/app
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
